# Generated by Django 4.2.2 on 2023-06-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlacePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlaceName', models.CharField(max_length=50)),
                ('PlaceExplain', models.TextField()),
                ('PlacePhoto', models.ImageField(upload_to='request/')),
            ],
        ),
        migrations.CreateModel(
            name='reportZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gu', models.CharField(max_length=10)),
                ('gubun', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=200)),
                ('manage', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='smoking_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, null=True)),
                ('facility_name', models.CharField(max_length=100, null=True)),
                ('facility_type', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('size', models.CharField(max_length=100, null=True)),
                ('date', models.CharField(max_length=100, null=True)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('management_status', models.CharField(max_length=100, null=True)),
                ('management', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='smokingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gu', models.CharField(max_length=10)),
                ('gubun', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=200)),
                ('manage', models.CharField(max_length=200)),
            ],
        ),
    ]
