# Generated by Django 4.2 on 2023-06-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placepost',
            name='PlaceName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
