# Generated by Django 4.2.2 on 2023-06-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gu', models.CharField(max_length=10)),
                ('gubun', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=200)),
                ('manage', models.CharField(max_length=200)),
            ],
        ),
    ]
