# Generated by Django 4.2 on 2023-06-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_placepost_placename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placepost',
            name='PlaceExplain',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='placepost',
            name='PlacePhoto',
            field=models.ImageField(null=True, upload_to='request/'),
        ),
    ]
